# Generated by Django 4.2.21 on 2025-06-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('hrapplications_two', '0008_alter_application_options_applicationacceptedfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRejectedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('filter_corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Rejected Application for Corp',
                'verbose_name_plural': 'Smart Filter: Rejected Application for Corp',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPendingReviewFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('filter_corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Application for Corp Pending Review',
                'verbose_name_plural': 'Smart Filter: Application for Corp Pending Review',
            },
        ),
        migrations.CreateModel(
            name='ApplicationInReviewFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('filter_corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Application for Corp In Review',
                'verbose_name_plural': 'Smart Filter: Application for Corp In Review',
            },
        ),
        migrations.CreateModel(
            name='ApplicationExistsFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('filter_corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo')),
            ],
            options={
                'verbose_name': 'Smart Filter: Application for Corp In Review',
                'verbose_name_plural': 'Smart Filter: Application for Corp In Review',
            },
        ),
    ]
