# Generated by Django 4.2.21 on 2025-06-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrapplications_two', '0009_applicationrejectedfilter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationexistsfilter',
            options={'verbose_name': 'Smart Filter: Application for Corp Exists', 'verbose_name_plural': 'Smart Filter: Application for Corp Exists'},
        ),
    ]
